In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import jax
import jax.numpy as jnp
import jax.random as r
import distrax as dx
import matplotlib.pyplot as plt

2024-10-31 17:01:43.551361: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1730394103.565984 2925336 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1730394103.570285 2925336 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [7]:
import flax.nnx as nnx

In [3]:
from typing import TypeVar

In [6]:
import sys
import os

# Navigate the current notebook directory to src directory
current_dir = os.getcwd()
jax_eco_dir = os.path.dirname(os.path.dirname(current_dir))
src_dir = os.path.join(jax_eco_dir, 'src')
sys.path.append(jax_eco_dir)

# Now you can import the module
import src.np_from_scratch as npfs

In [31]:
key0 = r.PRNGKey(0)

In [8]:
nnx.Linear?

Init signature: nnx.Linear(*args: 'Any', **kwargs: 'Any') -> 'Any'
Docstring:     
A linear transformation applied over the last dimension of the input.

Example usage::

  >>> from flax import nnx
  >>> import jax, jax.numpy as jnp

  >>> layer = nnx.Linear(in_features=3, out_features=4, rngs=nnx.Rngs(0))
  >>> jax.tree.map(jnp.shape, nnx.state(layer))
  State({
    'bias': VariableState(
      type=Param,
      value=(4,)
    ),
    'kernel': VariableState(
      type=Param,
      value=(3, 4)
    )
  })

Attributes:
  in_features: the number of input features.
  out_features: the number of output features.
  use_bias: whether to add a bias to the output (default: True).
  dtype: the dtype of the computation (default: infer from input and params).
  param_dtype: the dtype passed to parameter initializers (default: float32).
  precision: numerical precision of the computation see ``jax.lax.Precision``
    for details.
  kernel_init: initializer function for the weight matrix.
  bias_i

In [11]:
arr = jnp.arange(3).reshape(1, 3)
new = jnp.arange(2).reshape(2, 1)
# concatenate and broadcast new below arr to get array of dim 3 x 3
# first tile
new = jnp.tile(new, (1, 3))
# concatenate
new = jnp.concatenate([arr, new], axis=0)

In [12]:
new

Array([[0, 1, 2],
       [0, 0, 0],
       [1, 1, 1]], dtype=int32)

In [14]:
(1,) * 3 + (2,)

(1, 1, 1, 2)

In [16]:
jnp.split?

Signature:
jnp.split(
    ary: 'ArrayLike',
    indices_or_sections: 'int | Sequence[int] | ArrayLike',
    axis: 'int' = 0,
) -> 'list[Array]'
Docstring:
Split an array into sub-arrays.

JAX implementation of :func:`numpy.split`.

Args:
  ary: N-dimensional array-like object to split
  indices_or_sections: either a single integer or a sequence of indices.

    - if ``indices_or_sections`` is an integer *N*, then *N* must evenly divide
      ``ary.shape[axis]`` and ``ary`` will be divided into *N* equally-sized
      chunks along ``axis``.
    - if ``indices_or_sections`` is a sequence of integers, then these integers
      specify the boundary between unevenly-sized chunks along ``axis``; see
      examples below.

  axis: the axis along which to split; defaults to 0.

Returns:
  A list of arrays. If ``indices_or_sections`` is an integer *N*, then the list is
  of length *N*. If ``indices_or_sections`` is a sequence *seq*, then the list is
  is of length *len(seq) + 1*.

Examples:
  S

In [20]:
jnp.array_split(
    jnp.arange(6).reshape(2, 3),
    [1,2],
    axis=1
)

[Array([[0],
        [3]], dtype=int32),
 Array([[1],
        [4]], dtype=int32),
 Array([[2],
        [5]], dtype=int32)]

In [24]:
# consider a collection of 2D normal
locs = jnp.array([[0., 0.], [1., 1.], [2., 2.]])
scales = jnp.array([[1., 1.,]] * 3)

In [25]:
scales.shape

(3, 2)

In [29]:
mvns = dx.MultivariateNormalDiag(loc=locs, scale_diag=scales)

In [34]:
mvns.sample(sample_shape=5, seed=key0).shape

(5, 3, 2)

Note that the sample shape goes onto the first dimension.